### PR TITLE
Add pipeline extras cleanup

### PR DESCRIPTION
**Pull request by lasalvavida**
@lilleyse, can you look at this when you get a chance?

This reduces `addPipelineExtras` to not be quite so verbose. It also removes the `deleteExtras` qualification from removing pipeline extras, since there is currently no situation I am aware of where we want to export a gltf with pipeline extras.

### CODE REVIEW

**Comment by lilleyse** [comment]
Searching for `deleteExtras` there are still some occurrences left around.

**Comment by lilleyse** [comment]
Very nice, much cleaner. This also fixes an annoyance I was having in a the 3d tiles generator where some extras where sticking around in the extensions.

**Comment by lasalvavida** [comment]
> Searching for deleteExtras there are still some occurrences left around.

Ah yes, I did miss a few.

**Comment by lasalvavida** [comment]
Updated. I think I got them all this time. You may see some in your local doc folder if you have that generated, but built doc isn't in the repo.

**Comment by lilleyse** [comment]
Fixed a minor merge conflict just in the interest of time, looks good.

**Pull request merged**
