### PR TITLE
Fix for use with Cesium 1.36.

### PR DESCRIPTION
**Pull request by tfili**

### CODE REVIEW

**Comment by mramato** [comment]
@lilleyse I was going to merge and deploy this and I realized that master is out of date with the npm release.  Did you last ship 1.0.0 off of the `cleanup` branch? That's the only branch with package.json version set to 1.0.0 does that branch not even have a PR open.  Was this a mistake on your part?  What's going on here?  We really need to publish a new release ASAP but I need this cleared up first.

**Comment by mramato** [comment]
Thanks @tfili , I submitted some minor tweaks but this is good to go.  We just can't release until we clear up the `clean-up` confusion.

**Comment by mramato** [comment]
I think I figured out what happened.

1. @lilleyse pulled down master, updated CHANGES and package.json and released.
2. At some point switched to the `clean-up` branch
3. Realized he didn't submit his changes and committed 41c49a181e4682cfa67aff996b1abd2ea61db29d (which ended up going to the clean-up branch) and tagged it 1.0.0.
4. The expected changes never made it into master.

So I'm going to cherry-pick 41c49a181e4682cfa67aff996b1abd2ea61db29d  and call it a day.  When @lilleyse is back in the office he can clear up any remaining confusion and we can do a 1.0.2 if needed.

**Comment by lilleyse** [comment]
@mramato that sounds right to me, thanks for fixing it.

**Pull request merged**
