### PR TITLE
Speed up removeUnusedVertices

### PR DESCRIPTION
**Pull request by lasalvavida**
Only copy elements back a single time; speeds this up a bit.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Sounds great, do you have any before/after numbers?

**Comment by pjcozzi** [comment]
@lilleyse do you want to review?

**Comment by lasalvavida** [comment]
I found some issues while doing benchmarking, will fix and update

**Comment by lasalvavida** [comment]
This is good to go now

1.0 Brainstem is a good test model for this since it has lots of unused vertices.
Benchmarking results:

| | master | branch |
| -- | -- | -- |
| runtime | 226747ms | 56054 ms |

About a 4x speedup

**Comment by lilleyse** [comment]
Wow that's great, I'll review this soon.

**Comment by lilleyse** [comment]
The code looks good and works with all the models I've tried.

**Comment by pjcozzi** [comment]
Very nice, thanks @lasalvavida!

**Pull request merged**
