### PR TITLE
Shader fix

### PR DESCRIPTION
**Pull request by lilleyse**
Continuation of https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/194.

@lasalvavida can you also take a quick look through the repo for other cases like this in case I missed any?

### CODE REVIEW

**Comment by pjcozzi** [comment]
> @lasalvavida can you also take a quick look through the repo for other cases like this in case I missed any?

In the meantime, I will merge this.

@lilleyse please update CHANGES.md in master if it is warranted.

**Comment by lasalvavida** [comment]
Good catch @lilleyse, thank you!

**Comment by webprofusion-chrisc** [comment]
Trying the latest obj2gltf and running npm install to get latest dependencies, I then run obj2gltf and the output contains the following fragments (shaders section). I assume the fragmentShader shouldn't be text any more?

  "shaders": {
    "vertexShader0": {
      "type": 35633,
      "uri": "data:text/plain;base64,YXR0cmlidXRlIHZlYzIgYV90ZXhjb29yZF8wOwpwcmVjaXNpb24gaGlnaHAgZmxvYXQ7CnVuaWZvcm0gbWF0NCB1X21vZGVsVmlld01hdHJpeDsKdW5pZm9ybSBtYXQ0IHVfcHJvamVjdGlvbk1hdHJpeDsKdW5pZm9ybSBtYXQzIHVfbm9ybWFsTWF0cml4OwphdHRyaWJ1dGUgdmVjMyBhX3Bvc2l0aW9uOwp2YXJ5aW5nIHZlYzMgdl9wb3NpdGlvbkVDOwphdHRyaWJ1dGUgdmVjMyBhX25vcm1hbDsKdmFyeWluZyB2ZWMzIHZfbm9ybWFsOwp2b2lkIG1haW4odm9pZCkgewogIHZlYzQgcG9zID0gdV9tb2RlbFZpZXdNYXRyaXggKiB2ZWM0KGFfcG9zaXRpb24sMS4wKTsKICB2X3Bvc2l0aW9uRUMgPSBwb3MueHl6OwogIGdsX1Bvc2l0aW9uID0gdV9wcm9qZWN0aW9uTWF0cml4ICogcG9zOwogIHZfbm9ybWFsID0gdV9ub3JtYWxNYXRyaXggKiBhX25vcm1hbDsKfQo="
    },
    "fragmentShader0": {
      "type": 35632,
      "uri": "data:text/plain;base64,precision highp float;\nuniform vec4 u_ambient;\nuniform vec4 u_diffuse;\nuniform vec4 u_emission;\nuniform vec4 u_specular;\nuniform float u_shininess;\nuniform float u_transparency;\nvarying vec3 v_positionEC;\nvarying vec3 v_normal;\nvoid main(void) {\n  vec3 normal = normalize(v_normal);\n  vec4 diffuse = u_diffuse;\n  vec3 diffuseLight = vec3(0.0, 0.0, 0.0);\n  vec3 specular = u_specular.rgb;\n  vec3 specularLight = vec3(0.0, 0.0, 0.0);\n  vec3 emission = u_emission.rgb;\n  vec3 ambient = u_ambient.rgb;\n  vec3 viewDir = -normalize(v_positionEC);\n  vec3 ambientLight = vec3(0.0, 0.0, 0.0);\n  ambientLight += vec3(0.2, 0.2, 0.2);\n  vec3 l = vec3(0.0, 0.0, 1.0);\n  diffuseLight += vec3(1.0, 1.0, 1.0) * max(dot(normal,l), 0.);\n  vec3 h = normalize(l + viewDir);\n  float specularIntensity = max(0., pow(max(dot(normal, h), 0.), u_shininess));\n  specularLight += vec3(1.0, 1.0, 1.0) * specularIntensity;\n  vec3 color = vec3(0.0, 0.0, 0.0);\n  color += diffuse.rgb * diffuseLight;\n  color += specular * specularLight;\n  color += emission;\n  color += ambient * ambientLight;\n  gl_FragColor = vec4(color * diffuse.a, diffuse.a * u_transparency);\n}\n"
    }
  }

**Comment by lilleyse** [comment]
gltf-pipeline hasn't been published to npm since this change - I'll do that soon.

**Pull request merged**
