### PR TITLE
Fix byte boundary issue

### PR DESCRIPTION
**Pull request by lilleyse**
There was an issue related to byte offsets when loading models converted here into Cesium. Before an index accessor might look like:

```
    "accessor_2": {
      "bufferView": "bufferView_1",
      "byteOffset": 2,
      "byteStride": 0,
      "componentType": 5125,
      "count": 784734,
      "min": [
        0
      ],
      "max": [
        169568
      ],
      "type": "SCALAR"
    }
```

Which is valid since `accessor_2` is still 4-byte aligned when `bufferView_1` itself has the correct offset from the central `buffer`.

However since Cesium creates a typed array from the buffer view, and not the buffer as a whole, `accessor_2` would begin on byte 2 of a `Uint32Array`, causing the indices to be incorrect.

The fix here forces the first accessor of each target to start with a `byteOffset` of 0 to prevent situations like this.

@mramato can you test this?

### CODE REVIEW

**Comment by mramato** [comment]
Testing now.

**Comment by mramato** [comment]
I can confirm this fixes the problem I was seeing.  Thanks!

**Comment by mramato** [comment]
This also fixes #277, which was also offset related.

**Comment by mramato** [comment]
@lilleyse were you going to do more work here, or is this OK to merge? I know this module is still alpha, so not sure if we're doing unit tests yet or not.

**Comment by lilleyse** [comment]
Yeah I should add a unit test, I'll update soon.

**Comment by mramato** [comment]
Awesome, thanks.  I have a feeling this will fix quite a few issues I've ran into recently.

**Comment by lilleyse** [comment]
Added test.

**Comment by mramato** [comment]
Thanks @lilleyse!  The new test fails in master and passes with this fix.

**Comment by pjcozzi** [comment]
@lilleyse w.r.t the glTF spec does Cesium need a fix?  The _intent_ of the spec is to allow creating "pointers" with typed arrays instead of copying buffers.

**Comment by lilleyse** [comment]
Yeah Cesium would need a fix because nothing was wrong with the previous output. Cesium would need to adjust the byte offset of where it creates the index buffer's typed array.

Does the gltf spec allow an accessor to exist on a non-aligned byte offset? That would be a more serious issue, and require a copy.

**Comment by pjcozzi** [comment]
Please submit an issue to Cesium.

> Does the gltf spec allow an accessor to exist on a non-aligned byte offset? That would be a more serious issue, and require a copy.

@lexaknyazev?

**Comment by lexaknyazev** [comment]
@lilleyse @pjcozzi 
Here's relevant spec section.
https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#data-alignment

The intent is that no copy is needed.

**Comment by lilleyse** [comment]
Ok that is good to know. Thanks for pointing me there @lexaknyazev.

**Comment by lilleyse** [comment]
Closed https://github.com/AnalyticalGraphicsInc/cesium/issues/5309

**Pull request merged**
