### PR TITLE
Find accessor min and max from data if we're quantizing to avoid errors

### PR DESCRIPTION
**Pull request by lasalvavida**
@lilleyse For the converter

### CODE REVIEW

**Comment by lilleyse** [comment]
Tested, looks good.

**Comment by lilleyse** [comment]
Actually a test is failing.

**Comment by lasalvavida** [comment]
@lilleyse this should be good now

**Comment by pjcozzi** [comment]
Can we add a comment about why we are doing this?  As a workaround for invalid models, see #84.

I expect that this workaround will not be needed once the exporters/converters are updated.

**Pull request merged**
