### PR TITLE
Fix func call typo in getStatistics with node id

### PR DESCRIPTION
**Pull request by coryf**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Cool, good catch @coryf!  Can you please send in a CLA so we can merge this?  We use the same CLA as Cesium: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

@lilleyse any feedback?

**Comment by lilleyse** [comment]
Nothing from me, the changes look good.

**Comment by coryf** [comment]
:+1: CLA emailed

**Comment by pjcozzi** [comment]
Received, thanks again for contributing!

**Pull request merged**
