### PR TITLE
Write shader fix

### PR DESCRIPTION
**Pull request by lilleyse**
@mramato @lasalvavida 

Will publish 0.1.0-alpha8 right after this is merged.

### CODE REVIEW

**Comment by lasalvavida** [comment]
Why is this change necessary? I thought pipelineExtras source was always a Buffer? If it isn't for some reason, we should probably fix whatever made it a string.

**Comment by lasalvavida** [comment]
Taking a quick look, it looks like `compressTextureCoordinates` and `octEncodeNormals` write back the shader as a string. I don't know the use case that generated an error, but I suspect those are probably the culprits. They should write back a buffer instead of the modified string.

**Comment by mramato** [comment]
Thanks @lasalvavida, the library we were using was always creating a buffer so it looks like it was hiding the problem you describe.  @lilleyse, since the published version now has this issue; can we get this fixed and re-published soon?

**Comment by lilleyse** [comment]
Fixed the problem areas.

**Comment by lasalvavida** [comment]
Looks good to me, merge when ready

**Comment by mramato** [comment]
Unit test would be good, since this slipped past the ones we had.  Or at least write up an issue to add a test for this if there's simply no time right now.

**Comment by lasalvavida** [comment]
Good point. Checking for the buffer in the specs for compressTextureCoordinates and octEncodeNormals should be sufficient I think

**Comment by lilleyse** [comment]
Added tests.

**Comment by lasalvavida** [comment]
Looks good, merge and publish when ready

**Comment by mramato** [comment]
@lasalvavida you are free to merge PRs when you are confident they are good.  We want to foster a culture where anyone with write access can merge (they just assume partial responsibility if it's a bad change).  In either case, thanks again for catching the root cause.

**Comment by mramato** [comment]
Thanks @lilleyse!

**Comment by lilleyse** [comment]
Published 0.1.0-alpha8

**Pull request merged**
