### PR TITLE
Added script for generating Cesium AMD dependencies

### PR DESCRIPTION
**Pull request by lasalvavida**
@lilleyse or @pjcozzi, this PR adds the script for converting pipeline modules into AMD format for cesium

### CODE REVIEW

**Comment by lilleyse** [comment]
Add `dist` to .gitignore and .npmignore

**Comment by lilleyse** [comment]
Also exclude `dist` from `jsHintFiles`, `specFiles`, and the `coverage` task.

**Comment by pjcozzi** [comment]
Thanks @lasalvavida, this is a perfectly reasonable stopgap until we have bandwidth to do proper modules.

For my understanding, there is no browserify or related translation happening here, right?  Is this because these files aren't using any Node API that would need to be transpiled?

**Comment by lasalvavida** [comment]
> For my understanding, there is no browserify or related translation happening here, right?

Nope, no transpiling currently, so anything node-specific will not work. Currently only browser-friendly pipeline code will work with this which I think is probably acceptable for now.

**Comment by lilleyse** [comment]
One small suggestion, add newlines to the ends of newly created dist files.

The code looks solid to me. Once this is running in Cesium successfully this should be good to merge.

**Comment by pjcozzi** [comment]
All sounds good.  @lilleyse please merge when ready.

**Comment by lasalvavida** [comment]
@lilleyse, updated.

**Comment by pjcozzi** [comment]
LGTM

**Pull request merged**
