### PR TITLE
manual CRLF -> LF

### PR DESCRIPTION
**Pull request by likangning93**
Part of #392

### CODE REVIEW

**Comment by likangning93** [comment]
Test failures seem to be around binary gltf buffer stuff and how different line endings can throw that off... 
Seems like a sign that the existing tests are kind of fragile.

**Comment by likangning93** [comment]
> remove shader line endings from glb tests

This seemed like the "simplest" fix here, and it works for me both on Linux and Windows.
Let me know if it's too weird though.

**Comment by lilleyse** [comment]
This is fine for now. I just went through and made sure each file had a newline at the end. https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/399/commits/9a091f47290989935a82afb783394ac114fe0a06

**Comment by lilleyse** [comment]
Travis failed due to a timeout on a compression test.

**Pull request merged**
