### PR TITLE
Add support for WebP extension

### PR DESCRIPTION
**Pull request by OmarShehata**
This PR adds support for the [EXT_image_webp extension](https://github.com/KhronosGroup/glTF/pull/1534). It makes sure to take into account for the image defined in the extension if found when combining images into buffers.

### CODE REVIEW

**Comment by lilleyse** [comment]
Make sure to add a test. Otherwise looks good.

**Comment by OmarShehata** [comment]
@lilleyse just did! I didn't want to @ mention you until I did 😄

**Comment by lilleyse** [comment]
Actually, would it make sense to wait on this until a glTF extension is in place? Only png and jpeg are officially supported.

**Comment by OmarShehata** [comment]
I think that makes sense. I could start working on putting together a draft.

**Comment by pjcozzi** [comment]
Absolutely please write the extension concurrent to this; if the extension is held up then merge this to a non-master branch.  See https://github.com/KhronosGroup/glTF/issues/1503.

**Comment by OmarShehata** [comment]
I've expanded the scope of this PR. It should now correctly process glTF's with the proposed `EXT_image_webp` extension. I used this branch to generate the test model for the implementation in CesiumJS https://github.com/AnalyticalGraphicsInc/cesium/pull/7486

**Comment by OmarShehata** [comment]
Superseded by https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/450

**Pull request closed without merging**
