### PR TITLE
Make ForEach a proper static function

### LINKED ISSUE #310: Fix `ForEach` in 2.0 branch
https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/2.0/lib/ForEach.js#L12

`function ForEach() {}` should be `var ForEach = {}` instead.  `ForEach` doesn't need a constructor.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #310

### CODE REVIEW

**Comment by lilleyse** [comment]
Does `module.exports = ForEach` need to be at the bottom?

**Comment by hpinkos** [comment]
No, it just has to be after `var ForEach = {}`.  I just thought organizationally it made more sense to put it at the bottom

**Comment by lilleyse** [comment]
Maybe that's why we used `function ForEach() {}` instead of `var ForEach = {}`, so that the `module.exports` could go in the same place for all files. Is this change mainly for style purposes?

**Comment by hpinkos** [comment]
`ForEach` is a static class, so it shouldn't have a constructor

**Comment by lilleyse** [comment]
Ok, sounds good then.

**Pull request merged**
