### PR TITLE
Create editorconfig file

### PR DESCRIPTION
**Pull request by theTardigrade**

### CODE REVIEW

**Comment by lilleyse** [comment]
Thanks @theTardigrade !

**Comment by lilleyse** [comment]
Do we have a CLA from you? https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by lilleyse** [comment]
@theTardigrade Have you had a chance to fill out a CLA?

**Comment by theTardigrade** [comment]
Sorry, no CLA. I'm not really involved with your project, but just thought I'd contribute something simple. Though it may be simpler for someone else to copy and commit the file since it's so small, so I don't have to sign the form.

**Comment by lilleyse** [comment]
Alright, I'll close this and related PRs.

**Pull request closed without merging**
