### PR TITLE
Add deploy instructions

### LINKED ISSUE #206: Add publish instructions to README.md
and give me access to publish, please :)

I suppose it is:
* Update the version in `package.json` to match the latest version in CHANGES.md, then run
```
npm run prepublish
npm publish
```

### PR DESCRIPTION
**Pull request by pjcozzi**
Fixes #206

### CODE REVIEW

**Comment by lilleyse** [comment]
In the Node guide there is a more involved checklist of steps which involves publishing a release to github as well and testing that the package installs correctly locally. Should those details be here as well?

**Comment by pjcozzi** [comment]
Whatever is the standard approach.  Please update.

**Comment by pjcozzi** [comment]
@shehzan10 do you want to finish this?  Email me if you need help finding the Node Guide.

**Comment by shehzan10** [comment]
@pjcozzi Sure I can look into it.

**Comment by pjcozzi** [comment]
Replaced by #217.

**Pull request closed without merging**
