### PR TITLE
Make removeUnusedVertices use uninterleaveAndPackBuffers

### LINKED ISSUE #57: The removeUnusedVertices stage of the pipeline mangled a model
The model in question is the chinese dragon model from [here](https://github.com/SaschaWillems/Vulkan/blob/master/models/chinesedragon.obj).

I ran it through obj2gltf to produce this [valid gltf](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/298298/chinesedragon.zip).

dragon-normal

Remove unusedVertices outputs [this](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/298302/chinesedragon-mangled.zip).

chinese-dragon-mangled

### PR DESCRIPTION
**Pull request by lasalvavida**
Resolves #57.

I think this is also more readable.
Maybe consider renaming to removeUnusedAttributeValues or something similar since I think that may be a more accurate description.

### CODE REVIEW

**Comment by lasalvavida** [comment]
Found the cause of the CI failures: Node needs to be a higher version to use Buffer.read{...}LE() functions. This should fix the web3d branch as well.

**Comment by lasalvavida** [comment]
I still need to make sure this can handle the case where different primitives use the same accessors with different indices.

**Comment by lasalvavida** [comment]
@lilleyse Could you look at this when you get a chance? Just integrated the tests that @likangning93 wrote from master and they pass with this version of removeUnusedVertices.

@leerichard42 I'd also be very interested in your feedback here.

**Comment by lilleyse** [comment]
Sure I'll take a look soon.

**Comment by lasalvavida** [comment]
As far as the coverage situation goes the new removeUnusedVertices does have 100% coverage. The drop in percentage looks like it is from not all data types in numberOfComponentsForType being used and from removeUnusedVertices not having as many tests, so the hits/line is lower.

If this is something we think needs addressing, I'm open to suggestions.

**Comment by lilleyse** [comment]
Nothing much to say here, it looks great and the tests are very comprehensive.

As for the test coverage and naming, I think they're both fine.

**Comment by leerichard42** [comment]
Agreed, looks awesome! Thanks for fixing this up!

**Pull request merged**
