### PR TITLE
Update b3dm spec

### PR DESCRIPTION
**Pull request by tfili**
b3dm files now have an additional field for binaryBatchTableLength so the header is now 24-bytes. The batchLength was also moved to the end of the header. See spec https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/TileFormats/Batched3DModel/README.md.

Once this is merged old b3dm files won't work. I'm thinking we don't need the backwards compatibility, but we can if anyone feels strongly about it.

### CODE REVIEW

**Comment by pjcozzi** [comment]
This PR and much of the `b3dm-pipeline` branch do not belong in this project; this is project is for glTF, and should not include 3D Tiles unless strictly required.

@lasalvavida let's discuss when you are in.

**Comment by lasalvavida** [comment]
> This PR and much of the b3dm-pipeline branch do not belong in this project; this is project is for glTF, and should not include 3D Tiles unless strictly required.

Agreed, having a branch here was really only meant as a quick fix. This should probably be in 3D-Tiles-Tools, right?

**Comment by lilleyse** [comment]
Yeah the changes are in https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/6

**Comment by lasalvavida** [comment]
>Yeah the changes are in https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/6

That's not quite the same. This is `b3dm` in -> `b3dm` out and this branch has some changes that should be in the main pipeline and some that should be separated out since they're `b3dm` specific. Will open PRs.

**Pull request closed without merging**
