### PR TITLE
Added convertDagToTree stage

### PR DESCRIPTION
**Pull request by leerichard42**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Wow, @leerichard42, this looks great!  Did you also test with the model in https://github.com/AnalyticalGraphicsInc/cesium/issues/1754 and then drag-and-drop onto http://cesiumjs.org/convertmodel.html to confirm it works?

**Comment by leerichard42** [comment]
Success!
image

**Comment by pjcozzi** [comment]
Awesome!

**Comment by lilleyse** [comment]
Nice work @leerichard42 

This change also fixed a model that was having problems here: https://github.com/AnalyticalGraphicsInc/cesium/issues/3818

I attached it here in case it's useful for testing: [model.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/219505/model.zip)

**Pull request merged**
