### PR TITLE
Fix code samples in readme

### PR DESCRIPTION
**Pull request by lilleyse**

### CODE REVIEW

**Comment by lilleyse** [comment]
@shehzan10 could you review this quickly?

**Comment by shehzan10** [comment]
Changes look good and I verified that there are no other errors.

However, do we want to change `var` to `const`/`let`? `var` are currently eslint errors right, so maybe we should not use them in the readme either.

**Comment by lilleyse** [comment]
@shehzan10 Updated to use const.

**Comment by shehzan10** [comment]
Thanks @lilleyse.

**Pull request merged**
