### PR TITLE
Update build-cesium task for ES6

### PR DESCRIPTION
**Pull request by mramato**
This changes the Cesium build to output ES6 modules instead of AMD.  This is needed for Cesium's move to ES6.

@lilleyse are you the best person to review this?

We can hold off on merging until the Cesium PR is ready, but I wanted to get this opened  so I could reference it elsewhere.

### CODE REVIEW

**Comment by lilleyse** [comment]
@mramato Should everything after the imports be unindented now? Besides that looks good.

unindent

**Comment by mramato** [comment]
That's actually pretty tricky to do.  We don't actually touch any of the indented code, we just put back the string we get out of the source file. I might be able to do something about it, I'll see.

**Comment by mramato** [comment]
Cool, thanks.  I stand corrected.

**Comment by mramato** [comment]
@lilleyse this can be merged now that Cesium has merged ES6 support.

**Pull request merged**
