### PR TITLE
Added support for glTF 1.0.1 normalized to quantizeAttributes

### PR DESCRIPTION
**Pull request by lasalvavida**
Adds an optional flag to use the glTF 1.0.1 normalized property for higher precision decode matrices.

### CODE REVIEW

**Comment by lasalvavida** [comment]
Used to generate the test model for https://github.com/AnalyticalGraphicsInc/cesium/pull/4247

@lilleyse, can you look at this when you get a chance?

**Comment by lilleyse** [comment]
> @lilleyse, can you look at this when you get a chance?

Yes I'll check this out soon.

**Comment by pjcozzi** [comment]
CC @lexaknyazev - glTF 1.0.1

**Comment by pjcozzi** [comment]
I'm not following why this is needed.

**Comment by lasalvavida** [comment]
This is one of the advantages of having glTF 1.0.1. By adding the normalized flag to a quantized accessor, the decode matrix doesn't need to be stored as 1.0/65535.0. This gives you the option to generate quantized models that decode with higher precision.

**Comment by lilleyse** [comment]
+1 from me

**Comment by pjcozzi** [comment]
OK, does this still strictly conform to the extension or does that need an update?

**Comment by lasalvavida** [comment]
No updates needed, this strictly conforms to the extension.

**Pull request merged**
