### PR TITLE
Compressing integer accessors

### PR DESCRIPTION
**Pull request by lasalvavida**
For #120

- [x] Add utility for accessor type (this should exclude index accessors and doesn't currently) - just having bufferView and buffer accessible on AccessorReader is good enough. You can check the bufferView target from there.
- [x] Make functions that iterate over accessors use the added `AccessorReader` - Some of `removedUnusedVertices` was left alone because it is faster to copy data in chunks
- [x] Tests

Results look good except for cases where the first checkmark is an issue.

### CODE REVIEW

**Comment by lasalvavida** [comment]
Results: 

| | Box.gltf | CesiumMan.gltf | BrainStem.gltf |
| --- | --- | --- | --- |
| Original | 8.10 KB | 1.55 MB | 15.0 MB |
| w/o `compressIntegerAccessors` | 6.54 KB | 716 KB | 4.33 MB |
| w/ `compressIntegerAccessors` | 6.25 KB | 662 KB | 3.27 MB |

All models render correctly and this compression is completely lossless!
Just needs tests

**Comment by lilleyse** [comment]
Nice results! I'll check the code out when everything is ready.

**Comment by lasalvavida** [comment]
@lilleyse This should be ready for a look. Not super high priority, but it would be nice to get into master since it comes with a decent amount of cleanup as well.

**Comment by lilleyse** [comment]
Using `-q` is creating broken models on this branch.
capture5

**Comment by pjcozzi** [comment]
For **Box.gltf** above (https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/121#issuecomment-232410800), why is it smaller with integer compression?  What integer attributes did it have?

**Comment by lasalvavida** [comment]
> For Box.gltf above (#121 (comment)), why is it smaller with integer compression? What integer attributes did it have?

It's positions and normals are all made up of `0`, `1` or `-1`, which can be stored as a `byte` instead of a `float`.

**Comment by lasalvavida** [comment]
Good catch @lilleyse! This was an issue with `AccessorReader` that should be fixed now

**Comment by pjcozzi** [comment]
>> For Box.gltf above (#121 (comment)), why is it smaller with integer compression? What integer attributes did it have?

> It's positions and normals are all made up of 0, 1 or -1, which can be stored as a byte instead of a float.

Ah, OK.  Then it is rendered with bytes, right?

This is fine for now, but I would not be surprised if this is slower to render on many GPUs or if the data is padded / converted when uploaded to the WebGL buffer (e.g., we said bytes, but the driver converts to floats to get the fast path).

No need to do performance testing now since this is an edge case for most models.

**Comment by lasalvavida** [comment]
Yes, it is rendered with bytes. Definitely an edge case though; this is mostly for compressing `JOINT` that get stored as floats. I just wanted to show that rendering still worked for other semantics.

**Comment by pjcozzi** [comment]
All good with me, what's left before we can merge this?  https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/121#issuecomment-232481997?

**Comment by lasalvavida** [comment]
I don't have anything left on my list; should be good to merge.

**Comment by pjcozzi** [comment]
@lilleyse when you are ready...

**Comment by lilleyse** [comment]
I confirmed that quantization works normally now.

**Pull request merged**
