### PR TITLE
addDefaults doesn't add states.disable

### LINKED ISSUE #159: addDefaults.statesDefaults adds states.disable
This is not defined in the [glTF specification](https://github.com/KhronosGroup/glTF/tree/master/specification#states)

### PR DESCRIPTION
**Pull request by lasalvavida**
Resolves #159. After this change, pipeline models will pass validation: http://github.khronos.org/glTF-Validator/

@lilleyse or @pjcozzi  could you look at this when you get a chance? Should be a pretty easy merge.

### CODE REVIEW

**Comment by lilleyse** [comment]
Yup that was easy.

**Comment by emackey** [comment]
Hey guys, I think `states.disable` was from an old version of the spec, it's not there anymore.

https://github.com/KhronosGroup/glTF/blob/master/specification/schema/technique.states.schema.json

**Comment by lasalvavida** [comment]
> Hey guys, I think states.disable was from an old version of the spec, it's not there anymore.

Yes, that's why we removed here.

**Comment by emackey** [comment]
Wow, misread that, sorry!

**Pull request merged**
